name: coverage
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  eslint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Jest JUnit Test
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        run: |
          npm ci --legacy-peer-deps
          npm run test:cov:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # directory: ./coverage/ # not be used
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
